export const ADD_VEGA_VIEW = "ADD_VEGA_VIEW";
export const ALTER_VEGA_VIEW = "ALTER_VEGA_VIEW";
export const DELETE_VEGA_VIEW = "DELETE_VEGA_VIEW";
export const ADD_ANNOTATION_MARK = "ADD_ANNOTATION_MARK";
